### PR TITLE
Page style

### PR DESCRIPTION
**Pull request by mengiefen**
### In this iterations the following features are included:
- page styles improved
- media queries included to make the  page responsive for different device sizes
- The function to sort the score list from high score to low score

### CODE REVIEW

**Review by medaminedev66 — CHANGES_REQUESTED** [review]
Hi @mengiefen , :wave:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- ✔️Your design is wonderful.
- ✔️You have a descriptive PR

## Required Changes ♻️

- [ ] It would be better to add more steps to your README on how the user can use your project locally.  For example, the user should run `npm install` - then `npm start` ...
- [ ] The MIT link in your README is broken. Kindly fix this. Your README is the entry point of your users and having it well written without any broken links gives a good first impression and maximizes the potential of your product to your users.

_See the inline comments below for more required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/V

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mengiefen** [comment]
Hi @medaminedev66, 

Thank you so much for your suggestions.

Would you please clarify to me what N/V means?

**Comment by medaminedev66** [comment]
> Hi @medaminedev66,
> 
> Thank you so much for your suggestions.
> 
> Would you please clarify to me what N/V means?

Hi @mengiefen, It means there is nothing else to consider.

**Review by EricMbouwe — APPROVED** [review]
### Hi @mengiefen , 

# Status: Approved ✔️
Excellent job on this project. Keep it up 👏
Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
